---
- hosts: webserver
  become: yes
  remote_user: chris
  vars:
    packages:
    - nginx
    - git
    - certbot
    - python-certbot-nginx
  tasks:
    - name: ensure required packages are updated
      apt:
        name: "{{ packages }}"
        state: latest
    - name: ensure nginx is running
      service:
        name: nginx
        state: started
    - name: check out updated source
      git: # note that by default nginx hosts /var/www/html
        repo: 'https://github.com/Chris1712/personal-site.git'
        dest: /var/www/
