---
- hosts: webserver
  remote_user: root
  vars:
    packages:
    - nginx
    - git
  tasks:
    - name: ensure required packages is updated
      apt:
        name: "{{ packages }}"
        state: latest
#    - name: write nginx config file
#      template:
#        src: /somewhere/file
#        dest: /somewhere-else/file
#      notify:
#        - restart nginx
    - name: ensure nginx is running
      service:
        name: nginx
        state: started
    - name: check out updated source
      git:
        repo: 'https://github.com/Chris1712/personal-site.git'
        dest: /var/www/
